version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./development/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - plugin-network
  phpunit:
    image: php:8.0-cli
    # restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

  composer:
    container_name: composer
    image: composer
    command: /bin/bash "/app/commands/development/start-composer.sh"
    volumes:
      - ./:/app
    networks:
      - plugin-network
  npm:
    container_name: npm
    image: node:14.1.0-slim
    command: /bin/bash "/var/www/commands/development/start-npm.sh"
    volumes:
      - ./:/var/www
    networks:
      - plugin-network
  redis:
    image: redis:alpine
    container_name: redis-server
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
    - nsc-redis-data-prod:/data
    networks:
      - plugin-network
    ports:
      - "${REDIS_PORT}:6379"
  nginx:
    env_file:
      - .env
    container_name: nginx
    image: nginx:alpine
    ports:
      - "${SERVER_HTTP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./development/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - plugin-network
  database:
    env_file:
      - .env
    image: mysql:8.0
    container_name: database
    command:  mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    ports:
      - "${SERVER_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: laravel_plugin
      MYSQL_ROOT_PASSWORD: laravel_plugin
    volumes:
      - nsc-db-data:/var/lib/mysql
      - ./development/mysql/my.conf:/etc/mysql/my.conf
    networks:
      - plugin-network

networks:
  plugin-network:
    driver: bridge

volumes:
  nsc-db-data:
    driver: local
  nsc-redis-data-prod:
    driver: local
